[package]
name = "basis"
version = "0.1.0"
description = "Created with Anchor"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "basis"

[features]
no-entrypoint = []
cpi = ["no-entrypoint"]
default = []

[dependencies]
anchor-lang = "0.29.0"
anchor-spl = { version = "0.29.0" , features = ["token", "associated_token"] }
bytemuck = "1.14.0"
bincode = "1.3.3"
static_assertions = "1.1.0"
uint = "0.9.1"
num-traits = "0.2.15"
drift-macros = { git = "https://github.com/drift-labs/drift-macros.git", rev = "c57d87" }
borsh = "0.10.3"
solana-program = "1.16"
heapless = "0.8.0"
drift = { git = "https://github.com/drift-labs/protocol-v2.git", rev = "v2.95.0", features = ["cpi", "mainnet-beta"], default-features = false}
drift-vaults = { git = "https://github.com/drift-labs/drift-vaults.git", branch = "master", features = ["cpi"] }
solana-security-txt = "=1.1.0"